queryParameters:
  lat:
    description: Latitude of the center search coordinate. If used, lng is required.
    type: number
    example: 48.858844
    required: true
  lng:
    description: Longitude of the center search coordinate. If used, lat is required.
    type: number
    example: 2.294351
    required: true
  distance:
    description: Default is 1000m (distance=1000), max distance is 5000.
    type: integer
    maximum: 5000
    default: 1000
